jobs:
  publish:
    if: github.repository == 'apache/opennlp'
    name: Publish snapshot artifacts
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Cache Maven Repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 17
    - continue-on-error: true
      id: extract_version
      name: Extract version
      run: "VERSION=$(mvn exec:exec -Dexec.executable='echo' -Dexec.args='${project.version}'\
        \ --non-recursive -q)\nif [[ \"$VERSION\" == *\"SNAPSHOT\"* ]]; then\n   echo\
        \ \"snapshot=SNAPSHOT\" >> $GITHUB_OUTPUT\nfi\n"
      shell: bash
    - continue-on-error: true
      env:
        ASF_PASSWORD: ${{ secrets.NEXUS_PW }}
        ASF_USERNAME: ${{ secrets.NEXUS_USER }}
      if: steps.extract_version.outputs.snapshot == 'SNAPSHOT'
      name: Deploy Maven snapshots
      run: 'echo "<settings><servers><server><id>apache.snapshots.https</id><username>$ASF_USERNAME</username><password>$ASF_PASSWORD</password></server></servers></settings>"
        > settings.xml

        mvn --settings settings.xml -U -B -e -fae -ntp -DskipTests deploy

        '
name: Publish snapshot artifacts
on:
  repository_dispatch:
    types: trigger-ga___publish-snapshots.yml
